# Version format
version: "{build}"

image: Visual Studio 2015

# Environment variables
environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GVM_GO_VERSION: 1.17.6
  GVM_DL: https://github.com/andrewkroh/gvm/releases/download/v0.3.0/gvm-windows-amd64.exe

# Custom clone folder (variables are not expanded here).
clone_folder: c:\gopath\src\github.com\andrewkroh\gvm

# Cache gvm and Go until appveyor.yml is modified.
cache:
- C:\Users\appveyor\.gvm -> .appveyor.yml
- C:\Windows\System32\gvm.exe -> .appveyor.yml

# Scripts that run after cloning repository
install:
  - ps: >-
      if(!(Test-Path "C:\Windows\System32\gvm.exe")) {
        wget "$env:GVM_DL" -Outfile C:\Windows\System32\gvm.exe
      }
  - ps: gvm --format=powershell "$env:GVM_GO_VERSION" | Invoke-Expression
  - set PATH=%GOROOT%\bin;%PATH%
  - set PATH=%GOPATH%\bin;%PATH%
  - go version
  - go env

before_build:
  - go mod verify

build_script:
  # Compile
  - appveyor AddCompilationMessage "Starting Compile"
  - cd c:\gopath\src\github.com\andrewkroh\gvm
  - go build .\cmd\gvm
  - appveyor AddCompilationMessage "Compile Success"

test_script:
  # Unit tests
  - ps: Add-AppveyorTest "Unit Tests" -Outcome Running
  - go test -v ./...
  - ps: Update-AppveyorTest "Unit Tests" -Outcome Passed

# To disable deployment
deploy: off

# Notifications should only be setup using the AppVeyor UI so that
# forks can be created without inheriting the settings.

